(print(cons '(a b c) '()))
(print(list '(a b c) '()))
(print(append '(a b c) '())) 
(print(cons '(ser o no ser ) '(esa es la cuestion)) )
(print(list '(ser o no ser) '(esa es la cuestion)) )
(print(append '(ser o no ser) '(esa es la cuestion))) 
(print(list (first nil) (rest nil)) )
(print(append (first nil) (rest nil))) 
(print(cons (first nil) (rest nil)))

